"""empty message

Revision ID: 449d539f0f77
Revises: cd10b6af81fa
Create Date: 2021-12-13 09:34:59.460144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449d539f0f77'
down_revision = 'cd10b6af81fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'desc')
    # ### end Alembic commands ###
