"""empty message

Revision ID: 684929ebd9bf
Revises: e0b1e06496f1
Create Date: 2021-12-15 12:13:31.043715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684929ebd9bf'
down_revision = 'e0b1e06496f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    # ### end Alembic commands ###
