"""empty message

Revision ID: e660a1fed71a
Revises: 76fc9d9bd7bf
Create Date: 2021-12-15 10:10:47.728445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e660a1fed71a'
down_revision = '76fc9d9bd7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('username', sa.String(length=32), nullable=False))
    op.drop_index('user_id', table_name='user_table')
    op.create_unique_constraint(None, 'user_table', ['username'])
    op.drop_column('user_table', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'user_table', type_='unique')
    op.create_index('user_id', 'user_table', ['user_id'], unique=False)
    op.drop_column('user_table', 'username')
    # ### end Alembic commands ###
